# Generated by Django 4.2.7 on 2025-09-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='requires_attention',
            field=models.BooleanField(default=False),
        ),
    ]
