# Generated by Django 4.2.7 on 2025-09-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_conversation_requires_attention'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
